version: "3"
services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app

# docker-compose up -d
# docker compose down -v && docker rmi $(docker images -f “dangling=true” -q)